language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.m2/repository

before-install:
  - sudo apt-get install -y yarn

install:
  - pushd .. && git clone https://github.com/yang-tools/yang-lsp.git && popd

script:
  - pushd ../yang-lsp/yang-lsp && ./gradlew installDist && popd
  - pushd diagram && yarn run setup && yarn install && yarn run build && popd
  - pushd yang-eclipse && mvn clean install && popd

notifications:
  slack: theia-dev:wZFIkC6bV4WUqsnT6YxzGoMq