language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.m2/repository

before-install:
  - sudo apt-get install -y npm

install:
  - npm install -g yarn

script:
  - pushd diagram && yarn install && yarn run setup && yarn run build && popd
  - pushd yang-eclipse && mvn clean install && popd

notifications:
  slack: theia-dev:wZFIkC6bV4WUqsnT6YxzGoMq